PREFIX dcat:      <http://www.w3.org/ns/dcat#>
PREFIX dct:       <http://purl.org/dc/terms/>
PREFIX foaf:      <http://xmlns.com/foaf/0.1/>
PREFIX vcard:     <http://www.w3.org/2006/vcard/ns#>
PREFIX dcatap:    <http://data.europa.eu/r5r/>
PREFIX health:    <http://healthdataportal.eu/ns/health#>

CONSTRUCT {

    ###############################################################
    # Catalog
    ###############################################################

    ?catalog
        a dcat:Catalog ;
        dct:title ?title ;
        dct:description ?description ;
        dct:issued ?issued ;
        dct:modified ?now ;
        dct:language ?language ;
        dct:spatial
            <http://publications.europa.eu/resource/authority/country/NLD> ;
        dct:creator ?lumc ;
        dct:publisher ?lumc ;
        dcat:contactPoint ?contactPoint ;
        dcat:dataset ?dataset ;
        dcat:themeTaxonomy ?themeTaxonomy ;
        foaf:homepage ?homepage ;
        dcatap:applicableLegislation
            <http://data.europa.eu/eli/reg/2025/327/oj> .

    ###############################################################
    # Canonical LUMC Agent
    ###############################################################

    ?lumc
        a foaf:Agent ;
        dct:identifier "https://ror.org/05xvt9f17" ;
        foaf:name
            "Leiden University Medical Center"@en ,
            "Leids Universitair Medisch Centrum"@nl ;
        health:publisherNote
            "Het Leids Universitair Medisch Centrum (LUMC) is een universitair medisch centrum (umc). Wij hebben een actieve en innovatieve rol in de gezondheidszorg: regionaal, nationaal en internationaal. Dat is terug te zien in onze 3 kerntaken: patiëntenzorg, wetenschappelijk onderzoek en het opleiden van zorgprofessionals (onderwijs)."@nl ;
        health:publisherType
            <http://purl.org/adms/publishertype/Academia-ScientificOrganisation> ;
        dct:spatial
            <http://publications.europa.eu/resource/authority/country/NLD> ;
        foaf:homepage
            <https://www.lumc.nl/> ;
        foaf:mbox
            <mailto:lucid@lumc.nl> .

    ###############################################################
    # Contact Point
    ###############################################################

    ?contactPoint
        a vcard:Kind ;
        vcard:fn ?contactName ;
        vcard:hasEmail ?contactEmail .

}
WHERE {

    ?catalog a dcat:Catalog .

    BIND(NOW() AS ?now)

    BIND(
        IRI(CONCAT(STR(?catalog), "/organization/lumc"))
        AS ?lumc
    )

    OPTIONAL { ?catalog dct:title ?title }
    OPTIONAL { ?catalog dct:description ?description }
    OPTIONAL { ?catalog dct:issued ?issued }
    OPTIONAL { ?catalog dct:language ?language }

    OPTIONAL { ?catalog dcat:dataset ?dataset }

    OPTIONAL {
        ?catalog dcat:themeTaxonomy ?themeTaxonomy
    }

    OPTIONAL {
        ?catalog foaf:homepage ?homepage
    }

    OPTIONAL {
        ?catalog dcat:contactPoint ?contactPoint .

        OPTIONAL {
            ?contactPoint vcard:fn ?contactName
        }

        OPTIONAL {
            ?contactPoint vcard:hasEmail ?contactEmail
        }
    }
}